# Generated by Django 2.2 on 2019-10-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20191030_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='is_classics',
        ),
    ]
